version: 1.0.0
spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@0.0.0.0:27017
      database: admin
      repositories:
        type: none
  jms:
    servicebus:
      connection-string: Endpoint=sb://mydefault.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Ub4fQtGRsY5BR0BDGFkMdgnLCyIBtOqyYUCG5iyELYc=
      pricingTier: basic
